server {
    listen 80;
    server_name _;

    root /var/www/wan;
    index index.html;

    charset utf-8;

    location /_next/static/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        try_files $uri =404;
    }

    location ~* \.(?:html)$ {
        expires 5m;
        add_header Cache-Control "public, max-age=300";
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ $uri.html /index.html;
    }
}
